version: '3'

services:

  nginx:
    build: ./nginx
    ports:
      - "5555:80"
    volumes:
      - ./web_app/static_root:/code/static_root
      - ./web_app/static:/code/static
      - ./web_app/static/grappelli:/code/static/grappelli
      - ./web_app/media:/code/media
    depends_on:
      - web

  web:
    build: ./web_app
    env_file: ./my.env
    command: gunicorn -b 0.0.0.0:8000 --reload -w 4 super_news.wsgi
#    command: python manage.py collectstatic
#    command: /code/run.sh
    volumes:
     - .web_app:/.code
#      - ./web_app/static_root:/code/static_root
#      - ./web_app/static:/code/static
#      - ./web_app/media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    env_file: ./my.env
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
